# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

runtime: python27
api_version: 1
threadsafe: true
service: default

builtins:
- deferred: on

# Handlers define how to route requests to your application.
handlers:
- url: /api/v1/(.*)
  script: main.app

- url: /tasks/(.*) 
  script: main.app

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /favicon\.png
  static_files: build/favicon.png
  upload: build/favicon\.png

# unused for now
# - url: /service-worker\.js
#   static_files: build/service-worker.js
#   upload: build/service-worker\.js

- url: /manifest\.json
  static_files: build/manifest.json
  upload: build/manifest\.json

- url: /static/(.*)
  static_files: build/static/\1
  upload: build/static/(.*)
 
- url: .*
  static_files: build/index.html
  upload: build/index.html


# here if you want to use them.  See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK.  Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
#libraries:
#- name: jinja2
#  version: latest

libraries:
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"

skip_files:
- ^\.git$
- ^\client$
- ^\venv$

# needed for dev_appserver.py, tracks too many changes otherwise
- .*/zorya/client